### ISSUE TITLE
Getting this error while trying to start session.

### ISSUE THREAD

**Issue by kartic-techindustan** [comapi/comapi-sdk-android-samples#4]
E/FDN: F/FDN_1.3.0: Error starting session.
retrofit2.adapter.rxjava.HttpException: HTTP 403

**Comment by MarcinSwierczek** [comment]
Hi @kartic-techindustan,
Looks like you need to follow the steps in the prerequisites e.g. [here](https://github.com/comapi/comapi-sdk-android-samples/tree/master/chat/sample_memory#prerequisites). The JWT constructed in the demo app needs to match the authentication setup on the portal for the correct API space.
