### ISSUE TITLE
How to get Profile Id?

### ISSUE THREAD

**Issue by mansi-techindustan** [comapi/comapi-sdk-android-samples#5]
After creating new Profile for dot digital push notification we are getting "token", "API space Id, "issuer", "audience",
and "shared secret". But in the Sdk it is asking for Profile Id. Can you please explain how can we generate Profile Id for dot digital push notification android?

**Comment by DaveBaddeley** [comment]
Hi, please see here for an explanation of profiles and how and why the exist: https://developer.dotdigital.com/docs/registering-your-app-users-for-push
